export { Login } from './login/login'
export { VerifyOtp} from './verify-otp/verify-otp'
export { HomeComponent } from './home/home-component'
export { Table } from './table/table'
export { UncheckedQuestionsDetails } from './unchecked-questions/unchecked-questions'
export { QuestionDetailsComponent } from './question-details/question-details'
